### ISSUE TITLE
Schedule calendar display is off by one day

### ISSUE THREAD

**Issue by DeanCording** [openhab/openhab-core#1810]
In Openhab v3.0 M2, I have created a schedule rule to trigger on 05:50 every Monday to Friday:

    triggers:
      - id: "1"
        configuration:
          cronExpression: 0 50 5 ? * MON,TUE,WED,THU,FRI *
        type: timer.GenericCronTrigger`

In the schedule calendar display, it is shown on Tuesday to Saturday

![Schedule](https://user-images.githubusercontent.com/251170/98869177-197d6800-24bd-11eb-8cf0-74da60cf25d9.png)

**Comment by ghys** [comment]
Couldn't reproduce this so I was about to ask which timezone you're in, AU/NZ by any chance, and then I saw your profile... 😄 
This looks like an all-too-classical instance of an UTC date converted to a local date somewhere.
(this is a purely webui issue - someone please transfer if you can).

**Comment by DarkPatch** [comment]
Can Confirm I'm seeing similar problems.  

```
configuration: {}
triggers:
  - id: "1"
    configuration:
      cronExpression: 0 35 23 ? * WED *
    type: timer.GenericCronTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: ZWaveNode02239354ZW4009SmartToggleSwitchHallwayCloset_Switch
      command: ON
    type: core.ItemCommandAction



configuration: {}
triggers:
  - id: "1"
    configuration:
      cronExpression: 0 40 23 ? * 4 *
    type: timer.GenericCronTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: ZWaveNode02239354ZW4009SmartToggleSwitchHallwayCloset_Switch
      command: ON
    type: core.ItemCommandAction
```
The above are listed as Test and Test2
![image](https://user-images.githubusercontent.com/2498409/159858058-008224ad-9b99-46b4-b6ba-4d3b78fa9ddb.png)

Both events triggered on Wednesday.  
My timezone is currently configured for GMT-8  ( PST ) 
![image](https://user-images.githubusercontent.com/2498409/159859740-dcb856e4-9faa-4c34-84e5-dd0e89e3ae33.png)


Note: There is a secondary issue where the text for the trigger shows one day after the index number.   #2061
