### ISSUE TITLE
[OH3] Defining Rules in Main UI increases CPU Load

### ISSUE THREAD

**Issue by gdolfen** [openhab/openhab-core#1877]
I have a problem with high cpu usage in M2 and M3.
I figuerd out that the reason are rules which are configure over main ui.
I started with 4 rules in a *.rules file with a cpu usage of 1%. In main ui they always stay on "IDLE" after migration them to main ui by copy the generated code by the code view everything was fine, but the logs was full with ERRORs "No pre-parsed script found for e3dc-2". So I deleted the line "// context: e3dc-2" from the code and the log disappears, but the cpu was increased up to 5% per rule and the state stays always on "RUNNING".
Here is my rule code:

```
triggers:
  - id: "0"
    configuration:
      itemName: E3DC_Extern
    type: core.ItemStateChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: script
    configuration:
      type: application/vnd.openhab.dsl.rule
      script: |
        // context: e3dc-2
        var Number negativeValue = E3DC_Extern.state as Number
        var Number positiveValue = negativeValue * -1
        E3DC_String3.postUpdate(positiveValue)
    type: script.ScriptAction
```
It seemed that the rule is parsed every time, because every 5 seconds (5 seconds update period of item E3DC_Extern) I got the log error. Maybe preparsing the rule after saving it in main ui makes the trick.
