### ISSUE TITLE
[HTTP-OH3] buffer size overflow with larger JSON

### ISSUE THREAD

**Issue by binderth** [openhab/openhab-core#1938]
Trying to receive a JSON from Mowas (https://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json), I get the following WARN in log and the channel is still NULL:
```
2020-12-15 13:34:33.920 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'https://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json' (method='GET', content='null') failed: Buffering capacity 2097152 exceeded
```
The binding doesn't seem to give me the opportunity to define the buffer size.

My Thing and channel definition:
```
UID: http:url:mowas
label: HTTP Gefahren MoWas
thingTypeUID: http:url
configuration:
  authMode: BASIC
  ignoreSSLErrors: false
  baseURL: https://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json
  refresh: 600
  commandMethod: GET
  contentType: application/json
  timeout: 3000
channels:
  - id: mowasJSON
    channelTypeUID: http:string
    label: JSON von Mowas
    description: ""
    configuration: {}
```
