### ISSUE TITLE
Ephemeris conditions not evaluated for schedule

### ISSUE THREAD

**Issue by soenkekueper** [openhab/openhab-core#2044]
Hey,

when configuring rules with ephemeris conditions, this are not evaluated when displaying the rules in the schedule - which makes the schedule incorrect and useless because the information displayed are wrong :(

When configuring the rule with an "DayOfWeekCondition" like so:
```
triggers:
  - id: "1"
    configuration:
      time: 10:00
    type: timer.TimeOfDayTrigger
conditions:
  - inputs: {}
    id: "2"
    configuration:
      days:
        - SAT
        - SUN
    type: timer.DayOfWeekCondition
actions: []

```

It will be displayed correct within the schedule:
<img width="707" alt="Schedule_daysOfWeek" src="https://user-images.githubusercontent.com/24605357/103441885-7097f180-4c51-11eb-8a6a-1c7f099486ca.PNG">

When using the "WeekendCondition"
```
triggers:
  - id: "1"
    configuration:
      time: 10:00
    type: timer.TimeOfDayTrigger
conditions:
  - inputs: {}
    id: "2"
    configuration: {}
    type: ephemeris.WeekendCondition
actions: []
```
the rule will be displayed all days:
<img width="710" alt="Schedule_weekend" src="https://user-images.githubusercontent.com/24605357/103441895-8a393900-4c51-11eb-9d8f-75845cbb3881.PNG">

The epemeris configuration is set as saturday and sunday to be weekend:
<img width="791" alt="ephemeris_settings" src="https://user-images.githubusercontent.com/24605357/103441904-9ae9af00-4c51-11eb-86ab-41da6d82f37c.PNG">

This applies to all the ephemeris conditions - like holidays too.
