### ISSUE TITLE
Improve ECMA integration

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-core#2056]
The built-in executeCommandLine command doen't work in rules:

```
Rule:
triggers:
  - id: "1"
    configuration:
      cronExpression: 0 0 8 * * ? *
    type: timer.GenericCronTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/javascript
      script: executeCommandLine("/etc/openhab/bla.sh");
    type: script.ScriptAction

```

Result in the logfile:

`2021-01-02 23:00:43.873 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'test' failed: ReferenceError: "executeCommandLine" is not defined in <eval> at line number 1
`

DSL rules don't show this problem - calling executeCommandLine there works fine.
