### ISSUE TITLE
Cron builder uses wrong day

### ISSUE THREAD

**Issue by questionmark78** [openhab/openhab-core#2061]
I used the cron builder in the Rules on OH3 to have a trigger on the first Monday of the month.
<img width="634" alt="Screenshot 2021-01-03 at 12 12 53" src="https://user-images.githubusercontent.com/724963/103477255-6135b700-4dbd-11eb-96b4-7e4816af14fd.png">

But it triggered on a Sunday.

**Comment by Hilbrand** [comment]
This seems to me a UI bug. 1 is Sunday. For example see https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm

**Comment by DarkPatch** [comment]
Tested using both WED and 4 and both activated on the correct day.  

The UI is displaying the wrong text for the day of the week, one day in advance.
```
configuration: {}
triggers:
  - id: "1"
    configuration:
      cronExpression: 0 40 23 ? * 4 *
    type: timer.GenericCronTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: ZWaveNode02239354ZW4009SmartToggleSwitchHallwayCloset_Switch
      command: ON
    type: core.ItemCommandAction
```
![image](https://user-images.githubusercontent.com/2498409/159859005-71a23cfd-a523-44f4-9b74-2dc5724e4cfc.png)

1. Sunday
2. Monday
3. Tuesday
4. Wednesday
5. Thursday
6. Friday
7. Saturday

My timezone is set for PST (GMT-8) 
I tried changing my timezone to GMT  but saw no change.
