### ISSUE TITLE
API Performance

### ISSUE THREAD

**Issue by dlaplexurenet** [openhab/openhab-core#2109]
I don't know if I have an exceptional huge config with around 220 things and more than 1400 items, but I can see that this is causing some performance issues with the API.

I use a lot the Add Items from Textual Definition and after a restart of OpenHAB it's rather fast (but still not really snappy) and after a couple of days it takes up to 9s to load 220 things and 30s to load the items (compared to 2s for things and 6s for items after a restart).

I don't think this is really related to #1899

**Comment by bigbasec** [comment]
Just an FYI, you're not giving much information as far as the problem here.   What type of system is this running on?  What version of OH?   You'd probably get a little more attention on this if you expanded on the issue.

**Comment by dlaplexurenet** [comment]
Here are the technical information from main UI support page:

```
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_LU
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.8
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.41+75-CA
  osName: Linux
  osVersion: 5.10.5-v8+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 63579592
  totalMemory: 259522560
bindings:
  - airquality
  - astro
  - exec
  - gardena
  - homeconnect
  - hpprinter
  - hue
  - icalendar
  - irobot
  - km200
  - knx
  - logreader
  - mqtt
  - mystrom
  - netatmo
  - ntp
  - samsungtv
  - sonos
  - telegram
  - unifi
  - unifiprotect
  - weathercompany
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: N/A
    language: en-gb
    languages:
      - en-gb
    onLine: true
    platform: MacIntel
  screen:
    width: 2048
    height: 1280
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
timestamp: 2021-01-15T17:40:44.691Z
```

Fortunately, I do not face the issue right now (but I had to reboot the rpi recently because of a kernel update).

I don't know how I could reproduce the issue, else I would put more information. I just wonder if someone else is facing the same issue.
