### ISSUE TITLE
MainUi-Graphic-Issue, Non-Semantic Tags, and editing on mobile

### ISSUE THREAD

**Issue by bd8392** [openhab/openhab-core#2122]
Hi I discovered serveral MainUi issues (tested twice in upgraded oh and fresh Install)

1) I sometimes have vertical stripes through the tiles displaying my semantic-tagged equipment (when opened and zoomed in). This disappeares when reopened. (Latest chrome win10)

2) when you create an Item throughout a thing-channel, and switch the semantic-tag from point to none, an empty Non-Semantic tag is added.

3) you can't delete Non-Semantic Tags on mobile (that are empty have not tested with other ones)

All tested on RPI 4 with hypriot-os, latest docker and OpenHab 3.0.0

```
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_AT
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 200027584
  totalMemory: 485969920
bindings:
  - amazonechocontrol
  - astro
  - bluetooth
  - chromecast
  - gardena
  - harmonyhub
  - ipcamera
  - jablotron
  - kodi
  - mail
  - ntp
  - openweathermap
  - orvibo
  - samsungtv
  - smartthings
  - telegram
  - unifi
  - unifiedremote
  - upnpcontrol
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.141 Safari/537.36
timestamp: 2021-01-15T20:50:27.200Z
```
![vertical_stripe](https://user-images.githubusercontent.com/45922770/104777415-e8027080-577b-11eb-9e4f-b964885a70c6.png)
![empty-tag](https://user-images.githubusercontent.com/45922770/104777417-e9339d80-577b-11eb-94d9-4ee8a8ea4e83.png)
