### ISSUE TITLE
[Rules] Issues regarding only-if and Dimmer-value

### ISSUE THREAD

**Issue by bf8392** [openhab/openhab-core#2124]
Hi =), I try to define a simple rule under OH3 with the main UI…The syntax is the following:
When I turn on the “Küchendimmer” above a value of 80, it should turn on my “Arbeitsplattenlicht” and “Dunstabzugshaube” Items…The rule reacts, but as soon as I define the “only if item state > 80” the rule never runs…Here is the code of main-ui:
```
triggers:
  - id: "1"
    configuration:
      itemName: DimmerKuechenlicht
    type: core.ItemStateUpdateTrigger
conditions:
  - inputs: {}
    id: "4"
    configuration:
      itemName: DimmerKuechenlicht
      state: "80"
      operator: ">"
    type: core.ItemStateCondition
actions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: Arbeitsplattenlicht_Switch
      command: ON
    type: core.ItemCommandAction
  - inputs: {}
    id: "3"
    configuration:
      itemName: Dunstabzugshaube
      command: ON
    type: core.ItemCommandAction
```
That is the Rule known working under “old” syntax:
```
rule "Kuechenbeleuchtung Regel"
when
    Item Dimmer_Kuechenlicht_Esstischlicht received update
then
    if (Dimmer_Kuechenlicht_Esstischlicht.state > 80) {
    Dunstabzugshaube.sendCommand(ON)
    Schalter_Arbeitsplattenlicht_Kueche.sendCommand(ON)
    }
    else {
    Dunstabzugshaube.sendCommand(OFF) 
    Schalter_Arbeitsplattenlicht_Kueche.sendCommand(OFF)
    }
end
```
I know the new rule will turn on AND off, but such a syntax is not possible under main-ui…
I just want to understand, why the rule is not working on the “new” main-ui syntax, or what I’m doing wrong here…

Platform Info: OpenHab Docker 3.0, hypriot OS latest, Rpi 4
```
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: de_AT
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 11.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.43+88-CA
  osName: Linux
  osVersion: 5.4.79-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 39943952
  totalMemory: 304283648
bindings:
  - amazonechocontrol
  - astro
  - bluetooth
  - chromecast
  - gardena
  - harmonyhub
  - ipcamera
  - jablotron
  - kodi
  - mail
  - ntp
  - openweathermap
  - orvibo
  - samsungtv
  - smartthings
  - telegram
  - unifi
  - unifiedremote
  - upnpcontrol
  - zwave
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.25
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1536
    height: 864
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/87.0.4280.141 Safari/537.36
timestamp: 2021-01-16T18:45:13.317Z
```
The Bug was confirmed by reproduction here: https://community.openhab.org/t/problem-with-rule-under-oh3/114383/13
