### ISSUE TITLE
OH3 Chart page config error

### ISSUE THREAD

**Issue by mebj** [openhab/openhab-core#2156]
**Expected behaviour**
Charts designed using multiple grids should display as separate items

**Current Behaviour**
I have tested created a chart page. Having one grid works well but when using two grids these become superimposed on each other instead of separate items and I cannot find any settings or workaround to change this.

Here is the design page:
![Capture](https://user-images.githubusercontent.com/10342504/105724744-7c14ca80-5f28-11eb-8258-82f07267d8ce.JPG)

Here is the resulting chart:
![Capture1](https://user-images.githubusercontent.com/10342504/105724854-95b61200-5f28-11eb-8a1a-917a3f5c24f5.JPG)

Here is the automatically generated YAML code:
```
config:
  label: TestChart
  sidebar: true
slots:
  grid:
    - component: oh-chart-grid
      config: {}
    - component: oh-chart-grid
      config: {}
  xAxis:
    - component: oh-time-axis
      config:
        gridIndex: 0
    - component: oh-time-axis
      config:
        gridIndex: 1
  yAxis:
    - component: oh-value-axis
      config:
        gridIndex: 0
        name: Grader
        min: "15"
        max: "35"
        nameLocation: center
        nameGap: 20
        nameRotate: "90"
    - component: oh-value-axis
      config:
        gridIndex: 1
        name: Grader
        min: "-30"
        max: "30"
        nameLocation: center
        nameGap: 20
        nameRotate: "90"
  series:
    - component: oh-time-series
      config:
        name: Temperatur nedre hall
        gridIndex: 0
        xAxisIndex: 0
        yAxisIndex: 0
        type: line
        item: Temp1_node1
    - component: oh-time-series
      config:
        name: Frys
        gridIndex: 1
        xAxisIndex: 1
        yAxisIndex: 1
        type: line
        item: Temp_node2_freezer
```
I am using latest OpenHabian release (OpenHab 3.0.0) on a RPi 4. I cannot test the behavior on any other setup to check if this is a specific Raspbian issue. Several searches on the Internet do not show similar error reports why my first impression was it was a handling error by myself but I cannot find any way to solve the problem.
