### ISSUE TITLE
Dynamic light icons (light, dimmer) do not work with color lights

### ISSUE THREAD

**Issue by mechalas** [openhab/openhab-core#2279]
I was directed to open an issue here per #https://github.com/openhab/openhab-addons/issues/10478

It appears that the dynamic icons do not adjust according to the brightness channel of a color light. For example, in the Main UI, if you set up (for example) a floor plan page, add a marker, and give it the following config:

```
component: oh-plan-marker
config:
  name: Downlight
  coords: 1330.1926950865668,1190.0514957769285
  item: MyDownlight_Color
  icon: oh:light
  iconUseState: true
slots:
  default: []
```

Then the icon will not change as the brightness of the light is changed: you always get the "default state" version of the icon. This seems to be because the item's state is returned as a triplet (H,S,B), and openHAB's icon-state-handling doesn't extract the brightness from the triplet when fetching the dynamic icon.

Running OH 3.0.1 on Ubuntu 20.04 LTS, x86_64 with Chromium-based browsers.
