### ISSUE TITLE
The "equals" condition does not work for the items storing dimensionless number values

### ISSUE THREAD

**Issue by mak-42** [openhab/openhab-core#2624]
I created the channel like this and linked it to the item "AqaraSmartHomeCube001_Side".
```
  - id: side
    channelTypeUID: mqtt:number
    label: Side
    description: null
    configuration:
      min: 0
      stateTopic: zigbee2mqtt/AqaraSmartHomeCube001
      transformationPattern: JSONPATH:$.side
      max: 6
```
I added the "But only if" condition to the rule like this:
```
conditions:
  - inputs: {}
    id: "4"
    configuration:
      itemName: AqaraSmartHomeCube001_Side
      state: "0"
      operator: "="
    type: core.ItemStateCondition
```

This condition always returns "false" even state of "AqaraSmartHomeCube001_Side" is equal to 0.

The problem is in the "org.openhab.core.automation.internal.module.handler.ItemStateConditionHandler". Look at the code (version 3.1.x, but i bet the version 3.2 has the same issue):
```
            Item item = itemRegistry.getItem(itemName);
            State compareState = TypeParser.parseState(item.getAcceptedDataTypes(), state);
            State itemState = item.getState();
            DecimalType decimalState = itemState.as(DecimalType.class);
            logger.debug("ItemStateCondition '{}'checking if {} (State={}) {} {}", module.getId(), itemName, itemState,
                    operator, compareState);
            switch (operator) {
                case "=":
                    logger.debug("ConditionSatisfied --> {}", itemState.equals(compareState));
                    return itemState.equals(compareState);
```
The "item.getAcceptedDataTypes()" returns "[class org.openhab.core.library.types.DecimalType, class org.openhab.core.library.types.QuantityType, class org.openhab.core.types.UnDefType]". It means the "TypeParser.parseState(item.getAcceptedDataTypes(), state)" returns object of "DecimalType" creating as "DecimalType.valueOf("0")". But the "item.getState()" returns the object of "QuantityType". The "compareState" and "itemState" have different types. and the equation "temState.equals(compareState)" never returns "true".

The safest way to solve it to rewrite the equation like this:
```
return (null != decimalState && compareState instanceof DecimalType && decimalState .equals((DecimalType)compareState)) ||  itemState.equals(compareState);
```
But I think the right path to fix it is to convert the "itemState" to the class of "compareState" before comparing.

I have found a workaround. The condition can be replaced by this couple which works well:
```
conditions:
  - inputs: {}
    id: "5"
    configuration:
      itemName: AqaraSmartHomeCube001_Side
      state: "0"
      operator: ">="
    type: core.ItemStateCondition
  - inputs: {}
    id: "4"
    configuration:
      itemName: AqaraSmartHomeCube001_Side
      state: "0"
      operator: <=
    type: core.ItemStateCondition
```
