### ISSUE TITLE
event is defined during rule execution with startup trigger

### ISSUE THREAD

**Issue by chaosjug** [openhab/openhab-core#2751]
I have a rule with two triggers:

```
configuration: {}
triggers:
  - id: "2"
    configuration:
      startlevel: 100
    type: core.SystemStartlevelTrigger
  - id: "1"
    configuration:
      itemName: myItem
    type: core.ItemStateChangeTrigger
conditions: []
```
If myItem is restored on startup, the rule is triggered twice on startup (which is what I would expect, once for the restored item plus once for the startup). The problem is, that in both cases "event" is defined during rule execution and pointing at one of the restored items.

If myItem is not restored on startup or if I remove the ItemStateChangeTrigger, the rule is triggered once and "event" is not defined during rule execution.

I'm using OpenHab 3.2 (openhabian)
