### ISSUE TITLE
3.3.0-m3 REST thing config error : "node_id=The parameter is required"

### ISSUE THREAD

**Issue by aplack-techfino** [openhab/openhab-core#2907]
Working with 3.3.0.M3 REST interface and have an interesting problem retrieving the config from things.  The CURL command is generating an error, and the error is generating a secondary error in the reporting.  I am more concerned about the first error, but the second should be addressed as well.

This is a Linux Ubuntu 20LTS server with Z-Wave gateway to the nodes (but Lutron devices giving the same issue) running 3.3.0-M3 from apt install.  
```Linux openhab 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```

All the devices have a node_id in their code, so this shouldn't be an issue.

```
2022-04-10 15:09:59.432 [DEBUG] [st.core.internal.thing.ThingResource] - Config description validation exception occurred for thingUID zwave:device:23dd704128:node2 - Messages: {node_id=The parameter is required.}
2022-04-10 15:09:59.433 [ERROR] [rg.apache.cxf.jaxrs.utils.JAXRSUtils] - No message body writer has been found for class java.util.Collections$UnmodifiableMap, ContentType: appplication/json
```

curl command:
```
curl -s -u oh.main.VALID_TOKEN: -X PUT 'http://192.168.1.254:8080/rest/things/zwave:device:23dd704128:node2/config' -H 'accept: appplication/json' -H 'Content-Type: application/json' -d '{ }'
```
No amount of fiddling with -d makes a difference.

node2 Code
```
UID: zwave:device:23dd704128:node2
label: "Z-Wave Node 002: DSC26 Micro Switch G2 Front Lawn Light"
thingTypeUID: zwave:aeon_dsc26_00_000
configuration:
  config_250_2: 0
  config_254_2: 0
  config_252_1: 0
  config_200_1: 1
  config_80_1: 2
  group_1:
    - controller
    - node_26
  config_2_2_0000FF00: 0
  group_2:
    - controller
    - node_26
  config_255_1_wo: 0
  switchall_mode: 0
  config_120_1: 1
  config_101_4: 4
  config_112_4: 3
  config_2_2_000000FF: 0
  config_102_4: 8
  config_113_4: 3
  config_111_4: 3
  config_103_4: 0
  node_id: 2
bridgeUID: zwave:serial_zstick:23dd704128
```

Karaf console Output
```
                           _   _     _     ____  
   ___   ___   ___   ___  | | | |   / \   | __ ) 
  / _ \ / _ \ / _ \ / _ \ | |_| |  / _ \  |  _ \ 
 | (_) | (_) |  __/| | | ||  _  | / ___ \ | |_) )
  \___/|  __/ \___/|_| |_||_| |_|/_/   \_\|____/ 
       |_|       3.3.0.M3 - Milestone Build

Use '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
To exit, use '<ctrl-d>' or 'logout'.

openhab> shell:info
Karaf
  Karaf version               4.3.6
  Karaf home                  /usr/share/openhab/runtime
  Karaf base                  /var/lib/openhab
  OSGi Framework              org.eclipse.osgi-3.16.300.v20210525-1715

JVM
  Java Virtual Machine        OpenJDK 64-Bit Server VM version 11.0.14.1+1-LTS
  Version                     11.0.14.1
  Vendor                      Azul Systems, Inc.
  Pid                         286211
  Uptime                      57 minutes
  Process CPU time            5 minutes
  Process CPU load            0.00
  System CPU load             1.00
  Open file descriptors       413
  Max file descriptors        102,642
  Total compile time          2 minutes
Threads
  Live threads                152
  Daemon threads              86
  Peak                        229
  Total started               5664
Memory
  Current heap size           212,915 kbytes
  Maximum heap size           2,009,088 kbytes
  Committed heap size         403,456 kbytes
  Pending objects             0
  Garbage collector           Name = 'G1 Young Generation', Collections = 183, Time = 2.015 seconds
  Garbage collector           Name = 'G1 Old Generation', Collections = 0, Time = 0.000 seconds
Classes
  Current classes loaded      21,969
  Total classes loaded        22,489
  Total classes unloaded      520
Operating system
  Name                        Linux version 5.13.0-39-generic
  Architecture                amd64
  Processors                  4
openhab>
```
