### ISSUE TITLE
RuleEngine tries to enable UI rules before automation addons have started

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-core#3272]
## Description

When openHAB starts up, the Rule Engine tries to load and activate UI rules, but fails with

```javascript
[ERROR] [ipt.internal.ScriptEngineManagerImpl] - ScriptEngine for language 'application/javascript;version=ECMAScript-2021' could not be found for identifier: 90826c44-30e5-4e92-badc-f3a1f8f56f6f
```

This problem seems to already exist in openHAB 3.4, but it was discovered on the openHAB 4 SNAPSHOTS.

See https://community.openhab.org/t/openhab-4-0-snapshot-discussion/142322/26?u=florian-h05 for NashornJS on openHAB 4.
See https://community.openhab.org/t/js-scripting-performance-problems-compared-to-nashhorn/142568?u=florian-h05 for GraalJS on openHAB 3.4.

## Steps To Reproduce

On openHAB 4.0:

1. Install the JS Scripting (Nashorn) addon
2. Create a UI rule with a system start level trigger using NashornJS
3. Restart openHAB
4. During openHAB startup, you'll watch such an error message

## Expected behaviour

The Rule Engine should wait for availability of the ScriptEngines provided by automation addons such as NashornJS or GraalJS before attempting to load or run a UI rule.

/cc @J-N-K

**Comment by J-N-K** [comment]
But that is expected behavior and IMO correct. You can create rules with more than one action, one in JS, one in DSL and one ItemCommandAction. If a script engine cannot be created, execution fails and that is logged. There is no way to detect if the scripting add-on is just not started or not installed.

a bug would be if that results in OH lock-up (like reported in the forum thread). I can‘t reproduce that.

**Comment by florian-h05** [comment]
The ScriptEngine creation fails because the addon is not loaded yet.
That`s because the rule engine is enabled before the automation addons are enabled.
IMO this is a bug, either the start level for the rule engine is too low or the start level for automation addons is too high.
If I rethink this, I would say that the automation addons start to late, they should have a lower start level to start before the rule engine.

**Comment by J-N-K** [comment]
But as I said: in an OSGi environment there is no guaranteed bundle loading/activation order (except dependencies). But since scripting add-ons are optional we can‘t know which are installed but not yet loaded (or even failing to load). 

Anyway, I‘ll have a look if we can improve the situation. But I fail to see how that would result in a total lock-up.

**Comment by florian-h05** [comment]
Okay thanks.
I think we are misunderstanting us a bit:

> But I fail to see how that would result in a total lock-up.

This issue is not about the big problem in the community post where openHAB stopped working.
This issue is only about the log message and the problem related to this, that start level triggers don't work.

**Comment by florian-h05** [comment]
IMO it's just a decision whether the Rule Engine starts later or the automation addons start earlier.

**Comment by J-N-K** [comment]
I can't reproduce it with the JS scripting add-on installed (maybe my test setup is too small to create significant delays in bundle-loading, but I do see the messages when I uninstall JS scripting. They stop immediately when I install the add-on, so it seems to work as expected.

We can't control which bundle is loaded first if we don't know which bundles need to be loaded. If we know that the rule engine needs language 1 and language 2, then we can make it wait for both to be activated (by using ready markers). 

But that is not the case here: The rule engine can work even if no language is installed at all: there are actions that do not depend on scripting.

**Comment by florian-h05** [comment]
I can only sometimes reproduce on my test setup using the following rule:

```yaml
configuration: {}
triggers:
  - id: "2"
    configuration:
      startlevel: 70
    type: core.SystemStartlevelTrigger
conditions: []
actions:
  - inputs: {}
    id: "1"
    configuration:
      blockSource: <xml xmlns="https://developers.google.com/blockly/xml"><block
        type="oh_print" id="rnN_-b6n(g|{_$sj:Q0;" x="144" y="161"><value
        name="message"><shadow type="text" id="kV1XotX;Xt%!N?vyRh`i"><field
        name="TEXT">Hello world</field></shadow></value></block></xml>
      type: application/javascript;version=ECMAScript-2021
      script: |
        print('Hello world');
    type: script.ScriptAction
```

> I can't reproduce it with the JS scripting add-on installed (maybe my test setup is too small to create significant delays in bundle-loading, but I do see the messages when I uninstall JS scripting. They stop immediately when I install the add-on, so it seems to work as expected.

Yes, I think bundle loading is just too fast on both our test systems, but this issue will definitely occur, because rule engine starts at start level 50 and automation addons have start level 80 (see https://github.com/openhab/openhab-addons/blob/a4a8d5d85f4d3d5ec148bf036255454dbf0a41f0/bundles/org.openhab.automation.jsscripting/src/main/feature/feature.xml#L8).

> But that is not the case here: The rule engine can work even if no language is installed at all: there are actions that do not depend on scripting.

I undertstand that.

> Besides the log messages (which may be a bit too high with ERROR): is there anything not working as expected?

Start level triggers simply don't work for file based rules and you can't use scripts as actions for UI rules with start level triggers.

WDYT about changing the start level of automation addons?
