### ISSUE TITLE
Broken database values (unit) after update to 3.4

### ISSUE THREAD

**Issue by travnick** [openhab/openhab-core#3306]
After update to OpenHab 3.4 I started to see values like 
![image](https://user-images.githubusercontent.com/619590/211344428-9847402e-58e9-4e27-b937-d8c3da7596f4.png)
instead of usual 20.98 ug/m3

Regardless that the unit of kg/m3 is totally quirky here, then values in database are stored as `0.00000000751` but previously was like `6.23`.
This leads to utterly broken interpretation of data on the charts 
![image](https://user-images.githubusercontent.com/619590/211345399-ea144a3e-17ab-4744-94a5-d88ce8d85ea1.png)
- so historical values of ug/m3 are now shown as kg/m3.

**Comment by J-N-K** [comment]
Add a state description with the proper unit and it‘ll work.

**Comment by travnick** [comment]
I've found a [documentation](https://www.openhab.org/docs/developer/bindings/thing-xml.html#state-description) but it totally unclear how to adjust it in the UI.
I've something like this in my channel cofiguration, and there is a `µg/m³` since very beginning:

```
channels:
  - id: airly_pm10
    channelTypeUID: http:number
    label: PM10
    description: null
    configuration:
      mode: READONLY
      stateTransformation: JSONPATH:$.current.values[?(@.name=='PM10')].value
      unit: µg/m³
```
