### ISSUE TITLE
System runlevel triggered rules trigger before done being saved

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-core#3713]
## Expected Behavior

Given the recent changes to system started/runlevel triggers so they *always* trigger if that runlevel has passed I would expect a UI rule to run after the "save" button is pressed.

## Current Behavior

After pressing "save" the rule attempts to run but because it's not yet ready an error is produced in the logs. 

```
2023-07-19 09:00:16.577 [ERROR] [e.automation.internal.RuleEngineImpl] - Failed to execute rule ‘time-statemachine' with status 'INITIALIZING'
```

## Possible Solution

Wait for the rule to become IDLE before attempting to trigger it or go back to the old behavior and don't run the rule at all on a save.

## Steps to Reproduce (for Bugs)

1. Create a rule in the UI (I'm seeing this with my Time Based State Machine rule template so you could use that if you want)
2. Open the Action and make a change.
3. Click "Save" and watch the error appear in the logs.

## Context

Errors in the logs while doing "normal" actions are alarming and will generate lots of forum traffic. 

Without watching the logs it is not apparent that the rule failed to run as expected. 

## Your Environment

* Version used: (e.g., openHAB and add-on versions) Snapshot #3538
* Environment name and version (e.g. Chrome 111, Java 17, Node.js 18.15, ...): Docker version
* Operating System and version (desktop or mobile, Windows 11, Raspbian Bullseye, ...): Docker version
```
runtimeInfo:
  version: 4.0.0
  buildString: "Build #3538"
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Debian
  osName: Linux
  osVersion: 5.15.0-76-generic
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 356040672
  totalMemory: 874512384
  startLevel: 100
bindings: null
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: true
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: macos
    pixelRatio: 2
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 12
    language: en-US
    languages:
      - en-US
      - en
    onLine: true
    platform: MacIntel
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
timestamp: 2023-07-19T15:07:38.366Z
```
