### ISSUE TITLE
Cron trigger in rules is more than 20 minutes delayed

### ISSUE THREAD

**Issue by sternegugger** [openhab/openhab-core#3998]
Using openHAB 4.1.0. 
A Rule is triggered by cron `cronExpression: 0 0 9 ? * MON,TUE,WED,THU,FRI *`. But the rule action runs allways more than 20 minutes delayed.

I already tried this, without success:
- Restart of ohenhab service
- Restart of OS (ubuntu)
- Deactivate for some minutes and activate the rule
- Shell command "date" shows correct time
- Using datetime in scripts (in OH rules) shows the correct time.
- Timezone in OpenHab and in OS is correct.

In the community I found a similar problem: https://community.openhab.org/t/everything-happens-51-minutes-too-late/132112
But there they solved the problem by a restart, which dit not work for me.

Does OH run an own clock? 

## Expected Behavior
The rule actions should be triggered in the same minute of the cron trigger

## Current Behavior
Example rule:
````
...
triggers:
  - id: "1"
    configuration:
      cronExpression: 0 0 9 ? * MON,TUE,WED,THU,FRI *
    type: timer.GenericCronTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      command: ON
      itemName: MQTTLED03_LED03onoff
    type: core.ItemCommandAction
...
````

Eventlog:
````
2023-12-14 09:24:34.188 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'MQTTLED03_LED03onoff' received command ON
````

Expected:
The event should be triggered at 9:00, not at 9:24

## Possible Solution
If OH uses an own clock, it should be synchonized with the OS clock.

## Steps to Reproduce (for Bugs)
On my system I can reproduce it with different cron and time triggers.
On a clean new OH installation, the bug would probably be not reprducable.

## Context
I am using OH since version 3.0.0 and updated it several times by ````sudo apt-get upgrade````.
In former times I did not have the time delay.

## Your Environment
* Version used: openHAB 4.1.0.
* Environment name and version: Chrome Browser 
* Operating System and version: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64), which runs on a virtual machine (virtualbox)
