### ISSUE TITLE
[RFC] Add proper support for dynamic channel creation for things

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab-core#4048]
More and more bindings dynamically create channels for an added thing.
While this makes it easy to support various variations of a device it does also lead to unexpected behaviour and really hard to track down issues. Some of these issues can be attribitued to bugs/issues in bindings but imho there should be some core changes to make things easier for both the binding developers and users.

For examples I use mostly the shelly binding because there I've observed the issues first hand:

1. After an openHAB restart the roller shutters dynamically create the channels. Due to some issue the rollershutter channel was not created for every roller shutter but the device still went online. So in the thing overview everything looked good, yet the command to close/open the shutters did not work because the link from the item was pointing nowhere.
2. Battery powered devices so they are asleep most of the time. After a restart they are stuck in "CONFIG PENDING" and will not report e.g. smoke/flood back to openhab. Typically they wake up every 24h but it's not enough for the binding to complete initialisation. Sometimes the devices are stuck for weeks, months and very often they never finish. In the best case they will not work until the first wake up.
3. The battery powered smoke alarm is especially tricky: Sometimes it changes to ONLINE, but the thing only has the channel for battery level but not for smoke alarm. In the event log it properly reports the battery level every 24h, but it will not report a smoke alarm even though the item and the corresponding link is correct.
4. When they are added and not yet discovered battery powered z-wave device are added as online, yet they do not have any channels at all and are not usable in any way.

# Improvement to things

Currently the thing lifecycle does not properly represent these steps. Thus it should be extended accordingly:

1. Currently we have the `INITIALIZING` status for things and only there should it possible to add channels to the things. Once it goes `ONLINE` the channels should be "frozen" and not be added/removed any more
2. A new status detail `CHANNEL_DISCOVERY`. If should be used when this thing is still being discovered. When using textual thing configuration and channels are provided there the `CHANNEL_DISCOVERY` should be skipped because the channels are supplied by the user. If there are no channels provided the `CHANNEL_DISCOVERY` should still run.
3. A new status detail `REGISTERING_OPENHAB`. Some things support sending notifications to a host controller. Most of the time this has to set up in some way so this should be the status after `CHANNEL_DISCOVERY`. Some device (e.g. Shelly) allow to set this persistent on the device so there should be an option to skip this is the user has done this.
4. Make it possible to share the discovered channels
Currently it's possible to share the thing through the `Code` tab. However without the discovered channels the same thing configuration will lead to totally different thing behavior depending on the device. Thus the discovered channels should also be shown in the Code tab.
5. Save/restore the discovered channels
I think this already implemented but currently it does not work for textually defined things. When channels are discovered they should be saved and after an openHAB restart restored accordingly assuming the device is still running correctly.
Some bindings implemented a custom storage (e.g. the `node_xxx.xml` of the z-wave binding) which should be standardized.
Some bingings also add possibilities to create thing types through parameters ([ecovacs](https://www.openhab.org/addons/bindings/ecovacs/#adding-support-for-unsupported-models)) which should also be standardized.
6. Add a validation for thing channels / config / etc
Sometimes devices change (e.g. firmware update) and the user forgets to re-add the thing to openhab. When the thing goes online there should be a one time check which validates everything and logs a warning/error in case of inconsistencies.

I'm aware that things more or less "work" right now but these issues are very hard to pin down even for experienced openHAB users and lead to very frustrating behavior (e.g. it works after one restart but doesn't after another),
Anything that makes `Things` more reproducable is worth the effort and a step in the right direction.

**Comment by rkoshak** [comment]
> Thus the discovered channels should also be shown in the Code tab.

I don't have any opinions on this RFC except that at least for Zwave and Zigbee, the discovered channels are shown in the Code tab. If they are not shown for other bindings (Shelly), maybe that part at least is a problem with the binding implementation instead of core?

> but currently it does not work for textually defined things. 

Isn't it the whole point of textually defined things to textually define everything and not do discovery? It seems very weird to me to have a textually defined Thing but not include the Channels in the textual definition. I'm totally on board with standardization of this sort of thing.

**Comment by spacemanspiff2007** [comment]
> ... at least for Zwave and Zigbee, the discovered channels are shown in the Code tab. 

This is what gets shown for a fully discovered Smart Color Button (Z-Wave) with multiple channels.
```yaml
UID: zwave:device:controller:node33
label: "Philio PSR04 (Node 33): Smart Color Button"
thingTypeUID: zwave:philio_psr04_00_000
configuration:
  config_1_1: 0
  config_2_1: 99
  config_10_1: 12
  wakeup_node: 1
  wakeup_interval: 86400
  group_1:
    - controller
  config_25_1: 0
  config_26_1: 1
  group_2:
    - controller
  node_id: 33
bridgeUID: zwave:serial_zstick:controller
```

For me it does not show the channels there (OH 4.0.0). Do you see something different?

> It seems very weird to me to have a textually defined Thing but not include the Channels in the textual definition.

Since the docs are always lacking the idea is to just define the plain thing and still have auto discovery / automatic channel creation. Once the device channels are properly discovered one can than edit the textual thing config to include the channel definition if desired (which then would be available from the code tab).
Basically discover what you use and then "freeze" that.

---

Another idea would be to have an additional thing state `TARGET_INITIALISATION` with the status detail `CHANNEL_DISCOVERY`and `REGISTERING_OPENHAB`.
That way the device states would clearly be decoupled from the thing initialization states which IMHO makes sense

**Comment by rkoshak** [comment]
> This is what gets shown for a fully discovered Smart Color Button (Z-Wave) with multiple channels.

That's weird as all of my Zwave and Zigbee (and Shelly for that matter) Things have all their Channels listed in the Code tab. 

Here are a few but I've looked at them all.

```
UID: zwave:device:zw_controller:node7
label: Home Energy Meter
thingTypeUID: zwave:aeon_dsb09_00_000
configuration:
  config_10_1: 5
  config_102_4_00000100: 0
  group_1:
    - controller
  config_102_4_00002000: 0
  config_101_4_00000008: 1
  config_101_4_00000800: 1
  config_101_4_00000004: 1
  config_101_4_00000400: 0
  config_112_4: 720
  config_101_4_00000001: 0
  config_101_4_00000002: 1
  config_101_4_00000200: 1
  config_103_4_00002000: 0
  config_103_4_00000100: 0
  config_255_4_wo: 0
  config_102_4_00001000: 0
  config_1_2: 110
  config_101_4_00001000: 1
  config_7_2: 25
  config_9_1: 5
  config_5_2: 25
  config_102_4_00000008: 0
  config_102_4_00000800: 0
  config_103_4_00001000: 0
  config_11_1: 5
  config_102_4_00000004: 0
  config_102_4_00000400: 0
  config_102_4_00000002: 0
  config_102_4_00000200: 0
  config_102_4_00000001: 0
  config_110_4_wo: 0
  config_113_4: 720
  config_101_4_00000100: 1
  config_111_4: 720
  config_101_4_00002000: 0
  config_103_4_00000001: 0
  config_103_4_00000002: 0
  config_103_4_00000200: 0
  config_103_4_00000004: 0
  config_103_4_00000400: 0
  config_3_1_00000008: 0
  config_103_4_00000008: 0
  config_103_4_00000800: 0
  config_3_1_00000004: 0
  config_3_1_00000002: 0
  config_3_1_00000001: 0
  config_100_4_wo: 0
  config_6_2: 25
  config_8_1: 5
  config_4_2: 25
  node_id: 7
bridgeUID: zwave:serial_zstick:zw_controller
location: Global
channels:
  - id: meter_watts
    channelTypeUID: zwave:meter_watts
    label: Electric meter (watts)
    description: Indicates the instantaneous power consumption
    configuration: {}
  - id: meter_kwh3
    channelTypeUID: zwave:meter_kwh
    label: Electric meter (kWh) 3
    description: Indicates the energy consumption (kWh)
    configuration: {}
  - id: meter_kwh2
    channelTypeUID: zwave:meter_kwh
    label: Electric meter (kWh) 2
    description: Indicates the energy consumption (kWh)
    configuration: {}
  - id: battery-level
    channelTypeUID: system:battery-level
    label: Battery Level
    description: null
    configuration: {}
  - id: meter_kwh
    channelTypeUID: zwave:meter_kwh
    label: Electric meter (kWh)
    description: Indicates the energy consumption (kWh)
    configuration: {}
  - id: meter_reset
    channelTypeUID: zwave:meter_reset
    label: Reset Meter
    description: Reset the meter
    configuration: {}
  - id: meter_kwh1
    channelTypeUID: zwave:meter_kwh
    label: Electric meter (kWh) 1
    description: Indicates the energy consumption (kWh)
    configuration: {}
  - id: meter_watts1
    channelTypeUID: zwave:meter_watts
    label: Electric meter (watts) 1
    description: Indicates the instantaneous power consumption
    configuration: {}
  - id: meter_watts2
    channelTypeUID: zwave:meter_watts
    label: Electric meter (watts) 2
    description: Indicates the instantaneous power consumption
    configuration: {}
  - id: sensor_power2
    channelTypeUID: zwave:sensor_power
    label: Sensor (power) 2
    description: Indicates the energy consumption (kWh)
    configuration: {}
  - id: sensor_power
    channelTypeUID: zwave:sensor_power
    label: Sensor (power)
    description: Indicates the energy consumption (kWh)
    configuration: {}
  - id: sensor_power3
    channelTypeUID: zwave:sensor_power
    label: Sensor (power) 3
    description: Indicates the energy consumption (kWh)
    configuration: {}
  - id: meter_watts3
    channelTypeUID: zwave:meter_watts
    label: Electric meter (watts) 3
    description: Indicates the instantaneous power consumption
    configuration: {}
  - id: sensor_power1
    channelTypeUID: zwave:sensor_power
    label: Sensor (power) 1
    description: Indicates the energy consumption (kWh)
    configuration: {}


UID: zwave:device:zw_controller:node4
label: Family Room Outlet
thingTypeUID: zwave:ge_45605_00_000
configuration:
  switchall_mode: 255
  nodename_location: ""
  config_3_1: 0
  config_4_1: 0
  nodename_name: FamilyRoomLamp
  node_id: 4
bridgeUID: zwave:serial_zstick:zw_controller
location: Family Room
channels:
  - id: config_decimal_param3
    channelTypeUID: zwave:ge_45605_00_000_config_decimal_param3
    label: Night Light
    description: Defines the behavior of the blue LED.
    configuration: {}
  - id: switch_binary
    channelTypeUID: zwave:switch_binary
    label: Switch
    description: Switch the power on and off
    configuration: {}

UID: zigbee:device:zg_coordinator:0022a3000040d061
label: Front Porch Light Switch
thingTypeUID: zigbee:device
configuration:
  zigbee_macaddress: 0022A3000040D061
bridgeUID: zigbee:coordinator_ember:zg_coordinator
location: Front Yard
channels:
  - id: 0022A3000040D061_1_switch
    channelTypeUID: zigbee:switch_onoff
    label: "ON_OFF_LIGHT: Switch"
    description: null
    configuration:
      zigbee_reporting_polling: 900
  - id: 0022A3000040D061_3_switch
    channelTypeUID: zigbee:switch_onoff
    label: "ON_OFF_LIGHT_SWITCH: Switch"
    description: null
    configuration:
      zigbee_reporting_polling: 2147483647

UID: zigbee:device:zg_coordinator:282c02bfffe8f86f
label: Rich's Button
thingTypeUID: zigbee:device
configuration:
  zigbee_macaddress: 282C02BFFFE8F86F
bridgeUID: zigbee:coordinator_ember:zg_coordinator
channels:
  - id: 282C02BFFFE8F86F_1_batterylevel
    channelTypeUID: system:battery-level
    label: Battery Level
    description: null
    configuration:
      zigbee_reporting_polling: 7200
  - id: 282C02BFFFE8F86F_1_dimmer
    channelTypeUID: zigbee:switch_level
    label: "REMOTE_CONTROL: Level Control"
    description: null
    configuration:
      zigbee_reporting_polling: 2147483647
  - id: 282C02BFFFE8F86F_1_batteryalarm
    channelTypeUID: zigbee:battery_alarm
    label: Battery Alarm
    description: null
    configuration:
      zigbee_reporting_polling: 7200
  - id: 282C02BFFFE8F86F_1_batteryvoltage
    channelTypeUID: zigbee:battery_voltage
    label: Battery Voltage
    description: null
    configuration:
      zigbee_reporting_polling: 7200

```

The last Thing shown above was added last week so it's not just the old Things I have hanging around. 

I wonder what the difference is. Maybe you are doing a mixture of .things files and looking in MainUI? 

I cannot find a single one of my Zwave or Zigbee Things that does not list all the Channels in the Code tab. In truth I cannot figure out how you can even have a Thing with Channels showing on the Channels tab without them showing on the Code tab. Both the Channels tab and the Code tab are rendered from the same JSON so the UI would have to go out of it's way to *not* show the Channels in the Code tab and I can't think of a good reason to do that.

I'm on 4.1 but I don't recall ever not seeing the Channels in the code tab for any Thing that has Channels. All of my things are auto discovered where that's possible. 

Do you see Channels in the Channels tab? In the RAW JSON from the REST API?

> Since the docs are always lacking the idea is to just define the plain thing and still have auto discovery / automatic channel creation. Once the device channels are properly discovered one can than edit the textual thing config to include the channel definition if desired (which then would be available from the code tab).
Basically discover what you use and then "freeze" that.

Wouldn't all that become moot when the YAML config files become a thing? Then the user can discover the Thing and, if desired, export the whole lot to a text file in one step, possibly even through an export function. Is there a case where the Thing *has* to be manually defined but the Channels are discovered? All my experience is that either the Thing is completely discovered or the Thing is completely manually defined.
