### ISSUE TITLE
[Feature] Add support to format channel-type description using `html` tags 

### ISSUE THREAD

**Issue by pgfeller** [openhab/openhab-core#4269]
It is possible to use `html` elements to describe `thing-type` descriptions (see e.g. [z-wave binding](https://github.com/openhab/org.openhab.binding.zwave/blob/e16f1d8964c96c67fbf01b6a165b2470370ff2d0/src/main/resources/OH-INF/thing/aeon/dsb09_0_0.xml)).

➡️ it would be nice to have the same feature for `channel-type` descriptions as well. Using the same syntax as in for `thing-type` is rendered as plain text:

<details>
  <summary>thing:thing-descriptions</summary>

```xml

<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="huesync"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="https://openhab.org/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/thing-description/v1.0.0 https://openhab.org/schemas/thing-description-1.0.0.xsd">

	<channel-type id="execution-mode">
		<item-type>String</item-type>
		<label>Hue Sync operation mode</label>
		<description><![CDATA[<ul> <li><strong>video</strong> <p> Analyzes the on-screen visuals, translating colors and brightness into corresponding light effects for an immersive movie-watching experience. </p> </li> <li><strong>music</strong> <p> Analyzes the rhythm and beat of your music, creating dynamic light along to your tunes. </p> </li> <li><strong>game</strong> <p> Reacts to the action on your screen, intensifying the in-game atmosphere with bursts of light that correspond to explosions, gunfire, and other gameplay events. </p> </li> <li><strong>passthrough</strong></li> <li><strong>powersave</strong></li> <li>unknown <p> The device reports a mode not known to the binding (e.g. intorduced by a new firmware). <p> <strong>NOTE:</strong> It is not possible to send this command to the device. </p> </p> </li> </ul>]]></description>
		<command>
			<options>
				<option value="powersave"></option>
				<option value="passthrough"></option>
				<option value="video"></option>
				<option value="game"></option>
				<option value="music"></option>
				<option value="unknown"></option>
			</options>
		</command>
	</channel-type>
</thing:thing-descriptions>

```
</details>

The above declaration will produce the following visual representation in Main UI:

![image](https://github.com/openhab/openhab-core/assets/9395643/f2613aa6-3098-4dda-9a47-6c277b93a2a4)

It would improve the user experience if the content would support formatting as well and is rendered like for thing descriptions (example from z-wave binding):

![image](https://github.com/openhab/openhab-core/assets/9395643/9b1e3c20-efcf-478f-a716-38478e218214)

## Environment

<details>
  <summary>System Information (development system, single binding installed via folder)</summary>

```
runtimeInfo:
  version: 4.1.2
  buildString: Release Build
locale: de-CH
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.10
  javaVendor: Debian
  osName: Linux
  osVersion: 6.5.0-35-generic
  osArchitecture: amd64
  availableProcessors: 8
  freeMemory: 58478872
  totalMemory: 222298112
  uptime: 366
  startLevel: 100
addons: []

```
</details>
