### ISSUE TITLE
Model definition: semantic class, semantic property 

### ISSUE THREAD

**Issue by mti-sk** [openhab/openhab-core#4459]
In some cases, the basic selection of semantic class and semantic property is insufficient.
I have central heating, a horn/siren, a thermostatic valve, an air quality monitor, a gas leak sensor. I am not able to integrate these things into the existing semantic class and semantic property. I would like more configuration options.

In some cases, the basic selection of semantic class and semantic property is insufficient.
I have central heating, horn/siren, thermostatic valve, air quality monitor, gas leak sensor, infrared controller. I am not able to integrate these things into the existing semantic class and semantic property. I would like to request more configuration options.
I would suggest that these semantic class and semantic property can be freely configured (add new ones). So that it is not fixedly defined in the code.
I understand that this may be a fundamental change in the concept and as such can be very demanding.
**At a minimum, I would like to request the creation or addition of new semantic classes and semantic properties, namely: other!**
(a little different from none)
And maybe another: heating, notification, air (unifying class for CO, CO2, air quality)

## Your Environment
OpenHAB 4.2.2
Odroid N2+ (arm)

**Comment by clinique** [comment]
This is already possible https://github.com/openhab/openhab-core/pull/3659

**Comment by rkoshak** [comment]
I think this feature was never documented. I couldn't find it. 

Please close this issue and open a new issue on the openhab-docs repo to add documentation for how to add custom tags to the model.

To add a new tag create a .yml file in `$OH_CONF/tags`.

Here's an example:

```
version: 1


tags:
  - uid: Location_Home
    label: Home
    description: A house or home.
    synonyms:
      - House
      - Building

  - uid: Location_Indoor_Room_LivingRoom_Den
    label: Den
    description: A living room with a TV.
    synonyms:
      - Game room
      - TV room


  - uid: Location_Indoor_Room_LivingRoom_FrontRoom
    label: Front Room
    description: The front room of the house where guests are received.
    synonyms:
      - Sitting room
      - Music room

  - uid: Location_Indoor_Room_UtilityRoom
    label: Utility Room
    description: Room with HVAC, hot water heaters, laundry, etc.

  - uid: Equipment_Service
    label: Service
    description: A software service that provides something relevant to the home automation.
    synonyms:
      - Software
      - API
      - Daemon

  - uid: Equipment_MediaPlayer
    label: Media Player
    description: A device that can play media.
    synonyms:
      - Player
      - Speaker
      - Display

  - uid: Equipment_Occupancy
    label: Occupancy
    description: An equipment that monitors occupancy in a space.

  - uid: Point_BatteryProperty
    label: Battery Property
    description: A property of a battery.

  - uid: Property_Availability
    label: Availability
    description: Indicates the availability of a service or device.
    synonyms:
      - Online status
      - Offline status
      - Online/Offline status

  - uid: Property_Radon
    label: Radon
    description: Having to do with radon gas.

  - uid: Property_VOC
    label: VOC
    description: Having to do with volitile organic chemicals.

  - uid: Property_Media
    label: Media
    description: Streaming audio or video.
    synonyms:
      - Video
      - Music
      - Stream

  - uid: Property_Cost
    label: Cost
    description: The amount of money something requires.

  - uid: Property_Cloudiness
    label: Cloudiness
    description: Having to do with clouds.

  - uid: Property_Weather
    label: Weather
    description: Having to do with weather conditions.

  - uid: Property_Time
    label: Time
    description: Having to do with time.

  - uid: Property_Image
    label: Image
    description: Consisting or related to an image, perhaps from a camera.
```

It has examples of locations, equipment, points and properties.


Relevant openHAB forum post: https://community.openhab.org/t/oh-4-1-tutorial-to-manage-custom-semantic-tags/148135
