### ISSUE TITLE
Reloading of rules files doesn't work properly in openHAB 4.3.1

### ISSUE THREAD

**Issue by miloit** [openhab/openhab-core#4529]
Problem:
In openHAB 4.3.1, the reload of rules files does not function as expected. After making changes to the rules file, the system does not seem to reload the file correctly. The behavior can be observed when updating rule logic, such as changing item states or triggering certain conditions. The expected rule behavior does not occur unless the system is manually restarted or the rule files are reloaded multiple times.

Steps to reproduce:

Update or modify the rule file (e.g., changing triggers or actions).
Reload the rule file via the openHAB UI or CLI.
Observe that the rule file does not reload properly or the rule does not trigger as expected when conditions are met.
Expected behavior:
The rule file should reload successfully and execute the logic whenever the specified triggers or conditions are met, without requiring manual intervention like restarting the system.

Actual behavior:
The rule file does not reload automatically, and the modified rules do not seem to take effect until after a manual restart.

openHAB version:
4.3.1

Rule and Item Example:

seeing in the main.gui
```
// Example Rule Logic

// Triggers:
// - When item switch_LG_TV_Power changed
// - When item switch_systeminit changed from OFF to ON

// context: network-5
try {
    if (swith_LG_TV_Power == NULL && swith_LG_TV_Power == UNDEF) {
        logError("set switch_tvlivingroom_presence", "swith_LG_TV_Power NULL/UNDEF")
    } else {
        switch_tvlivingroom_presence.sendCommand(swith_LG_TV_Power.state.toString)
        logInfo("set switch_tvlivingroom_presence", switch_tvlivingroom_presence.state.toString())
    }
} catch (Throwable T) {
    logError("Error", "Some bad stuff happened in \"set switch_tvlivingroom_presence\": " + T.toString)
    if (switch_tvlivingroom_presence != NULL && switch_tvlivingroom_presence != UNDEF) {
        switch_tvlivingroom_presence.sendCommand(OFF)
    }
} finally {
    // No operation
}
```

in the file:

```rule "set switch_tvlivingroom_presence" when
    Item Switch_GF_Livingroom_TVPower changed or Item switch_systeminit changed from OFF to ON
then
    try {
        if (Switch_GF_Livingroom_TVPower == NULL && Switch_GF_Livingroom_TVPower == UNDEF) {
            logError("set switch_tvlivingroom_presence", "Switch_GF_Livingroom_TVPower NULL/UNDEF")
        } else {
            switch_tvlivingroom_presence.sendCommand(Switch_GF_Livingroom_TVPower.state.toString)
            logInfo("set switch_tvlivingroom_presence", switch_tvlivingroom_presence.state.toString())
        }
    } catch (Throwable T) {
        logError("Error", "Some bad stuff happened in \"set switch_tvlivingroom_presence\": " + T.toString)
        if (switch_tvlivingroom_presence != NULL && switch_tvlivingroom_presence != UNDEF) {
            switch_tvlivingroom_presence.sendCommand(OFF)
        }
    }
    finally {
        // No operation
    }
end```

**Comment by jimtng** [comment]
@miloit can you please fix the original post? There seem to be some missing information and incorrect formatting.

**Comment by miloit** [comment]
@jimtng what is missing?

And which formatting is wrong? But I guess it makes no sense to discuss because I am on oh5.1 now

**Comment by jimtng** [comment]
The last code fence you had seemed wrong, and missing the "rule xxxxxx" line.  I was hoping you would notice that yourself and correct it. However, when there’s no response after a simple request, it gives the impression that you’re no longer interested in the issue or that you’ve already resolved it without updating the status here.

The thing is that I don't experience this issue so to reproduce it, we need more help from you. Until we can reproduce this, it's hard to even start looking at something that isn't broken for ourselves.

Firstly, is this still an issue in 5.1 for you?



> But I guess it makes no sense to discuss because I am on oh5.1 now

I'm interpreting that as it is no longer an issue?

**Comment by miloit** [comment]
@jimtng It’s still there. It doesn’t happen every time, but it’s an error that occurs suddenly—especially when I try to fix or integrate a rule. Everything runs flawlessly for a while, and then all of a sudden nothing reloads anymore.
I don’t think there’s anything you can log in that situation either, because when it doesn’t reload, there’s nothing to log. You only notice it by the differences in behavior. Once you see it, you have to stop openHAB, clean the cache, and then everything works fine again.
The same thing happens with persistence files and item files.
I have many issues open across other projects as well, so I need to check and prioritize them to see which ones are more relevant. Because of that—and besides my own company and my family—I can’t regularly check everything in detail.


I try to generate a bash script I guess that's often open and change a file and close it and than check if it's loaded or not but I can't test it so early because right now I am in a hospital

**Comment by jimtng** [comment]
In Main UI Help & About, please copy paste your installation details. Knowing more about your system might help.

I have _never_ experienced such glitchy behaviour in file reloads on my system. Can you find anyone else reporting similar issues on the forums?

**Comment by miloit** [comment]
You can do this

#### What the script does (summary)
Opens /etc/openhab/thing/test.thing
Alternates between:

- deleting the last line, or adding a single newline

- If the file becomes empty, it writes the provided Thing definition

- Waits 2 minutes

- Checks /var/log/openhab/openhab.log to see if the file was loaded

- If not loaded, appends a timestamped entry to /root/openhabfilebasedtest.log

- Repeats forever with a configurable pause (default 30s)

```
/root/openhab_file_test.sh
and make executable with chmod +x /root/openhab_file_test.sh


#!/bin/bash

# ---------------- CONFIGURATION ----------------
THING_FILE="/etc/openhab/things/test.things"
OPENHAB_LOG="/var/log/openhab/openhab.log"
RESULT_LOG="/root/openhabfilebasedtest.log"

PAUSE_SECONDS=30          # configurable pause between cycles
CHECK_DELAY=10           # wait time before checking openhab.log (seconds)

THING_CONTENT='Thing huesync:box:LivingRoom "Philips Hue HDMI Sync Box, LivingRoom" [
     host="192.168.2.115",
     httpPollingInterval=60,
     apiAccessToken="yourTokenGoesHere=",
     registrationId="8",
     port=443,
     statusUpdateInterval=10
]'
# ------------------------------------------------

# Internal toggle state
STATE_FILE="/tmp/openhab_test_toggle.state"
[[ ! -f "$STATE_FILE" ]] && echo "delete" > "$STATE_FILE"

log_failure() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - test.things NOT loaded" >> "$RESULT_LOG"
}

echo "Starting OpenHAB Thing file test loop..."

while true; do
    ACTION=$(cat "$STATE_FILE")
    echo "Current action from state file: $ACTION"

    # Ensure Thing file exists
    touch "$THING_FILE"
    echo "Ensured Thing file exists: $THING_FILE"

    # If file is empty → write Thing content
    if [[ ! -s "$THING_FILE" ]]; then
        echo "$THING_CONTENT" > "$THING_FILE"
        echo "Thing content written to $THING_FILE"
    else
        if [[ "$ACTION" == "delete" ]]; then
            echo "Deleting last line of $THING_FILE..."
            sed -i '$d' "$THING_FILE"
            echo "State updated to 'newline'"
            echo "newline" > "$STATE_FILE"
        else
            echo "Adding a single newline to $THING_FILE..."
            echo "" >> "$THING_FILE"
            echo "State updated to 'delete'"
            echo "delete" > "$STATE_FILE"
        fi
    fi

    # Remember current log size to only check new entries
    LOG_SIZE_BEFORE=$(stat -c%s "$OPENHAB_LOG" 2>/dev/null || echo 0)
    echo "Recorded OpenHAB log size before checking: $LOG_SIZE_BEFORE bytes"

    # Wait before checking log
    echo "Waiting $CHECK_DELAY seconds before checking OpenHAB log..."
    sleep "$CHECK_DELAY"

    # Extract new log lines
    NEW_LOG=$(tail -c +$((LOG_SIZE_BEFORE + 1)) "$OPENHAB_LOG" 2>/dev/null)
    echo "Extracted new log entries from OpenHAB log."

    # Check if 'test.things' was loaded
    echo "Checking if 'test.things' was loaded in the OpenHAB log..."
    echo "$NEW_LOG" | grep -qi "Loading DSL model 'test\.things'"

    if [[ $? -ne 0 ]]; then
        echo "'test.things' not found in log. Logging failure..."
        log_failure
    else
        echo "'test.things' successfully loaded."
    fi

    # Pause before next iteration
    echo "Pausing $PAUSE_SECONDS seconds before next iteration..."
    sleep "$PAUSE_SECONDS"
done
```

#### Notes & Assumptions
The script runs continuously
It assumes OpenHAB logs mention test.thing when loaded
Requires root (or sufficient permissions) because:
/etc/openhab
/var/log/openhab
/root/*.log
Toggle state is stored in:
```

/tmp/openhab_test_toggle.state
```

**Comment by jimtng** [comment]
> Rule and Item Example:

1. So are the examples you've posted irrelevant, meaning it happens to any / all of your rules / config, and you mentioned persistence + items so it's not even about rules?
2. It sounds like it also affects UI based rules in addition to file based rules? So it's not really to do with the file-change notification system that detects changes in file and reloads it, but something inside core itself?

**Comment by jimtng** [comment]
> You can do this
> 
> #### What the script does (summary)

Have you done / run this on your problematic system? Can you post the results?

**Comment by miloit** [comment]
1. Yes, any file. I personally see it especially in .js files because often change it for testing 

2. Yes changes are not loaded also not displaying it in the main ui because it was not loaded

**Comment by miloit** [comment]
> > You can do this
> > #### What the script does (summary)
> 
> Have you done / run this on your problematic system? Can you post the results?

Yes....no access right now but I can send it in 1 week or more depending on my health situation

**Comment by miloit** [comment]
> In Main UI Help & About, please copy paste your installation details. Knowing more about your system might help.
> 
> I have _never_ experienced such glitchy behaviour in file reloads on my system. Can you find anyone else reporting similar issues on the forums?

```
runtimeInfo:
  version: 5.2.0
  buildString: "Build #5043"
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 21.0.9
  javaVendor: Eclipse Adoptium
  javaVendorVersion: Temurin-21.0.9+10
  osName: Linux
  osVersion: 6.12.47+rpt-rpi-v8
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 364571472
  totalMemory: 1008730112
  uptime: 148606
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-astro
  - binding-dwdpollenflug
  - binding-ephemeris
  - binding-exec
  - binding-http
  - binding-hue
  - binding-icalendar
  - binding-ipcamera
  - binding-kodi
  - binding-lgwebos
  - binding-logreader
  - binding-mail
  - binding-mqtt
  - binding-network
  - binding-ntp
  - binding-openuv
  - binding-openweathermap
  - binding-pihole
  - binding-sensorcommunity
  - binding-shelly
  - binding-solarforecast
  - binding-systeminfo
  - binding-telegram
  - binding-tr064
  - binding-volumio
  - binding-wled
  - binding-yamahareceiver
  - binding-yioremote
  - binding-zwavejs
  - misc-metrics
  - misc-openhabcloud
  - persistence-inmemory
  - persistence-jdbc-mariadb
  - transformation-exec
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - transformation-scale
  - transformation-xpath
  - transformation-xslt
  - ui-basic
  - voice-picotts
clientInfo:
  device:
    ios: false
    android: true
    androidChrome: true
    desktop: false
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    electron: false
    capacitor: false
    nwjs: false
    os: android
    osVersion: "16"
    webView: false
    webview: false
    standalone: false
    pixelRatio: 3
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - en-US
    onLine: true
    platform: Linux aarch64
  screen:
    width: 360
    height: 792
    colorDepth: 24
  support:
    touch: true
    pointerEvents: true
    passiveListener: true
    intersectionObserver: true
  themeOptions:
    dark: light
    autoDarkMode: true
    bars: light
    homeNavBar: default
    homeBackground: default
    disableExpandableCardAnimation: false
    blocklyRenderer: null
    disablePageTransitionAnimation: false
    hideChatInput: false
    webAudio: false
    visibleBreakpointDisabled: false
  userAgent: Mozilla/5.0 (Linux; Android 16; PHY110 Build/UKQ1.231108.001; wv)
    AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/144.0.7559.31
    Mobile Safari/537.36
timestamp: 2025-12-29T15:35:44.438Z
 ```

It's ab raspberry pi 4B 4GB with dietpi v9.20 running 

I hope I answered everything...please let me know if sth is open
