### ISSUE TITLE
Error in file generated thing configuration

### ISSUE THREAD

**Issue by miloit** [openhab/openhab-core#4607]
Hi OpenHAB Community,

I’m running into an issue with my Deye Inverter configuration. In the logs, I get the following warnings:

```
2025-02-16 11:43:21.437 [WARN ] [nding.http.internal.HttpThingHandler] - Cannot find channel implementation for channel http:url:deye:last-success.
2025-02-16 11:43:21.444 [WARN ] [nding.http.internal.HttpThingHandler] - Cannot find channel implementation for channel http:url:deye:last-failure.

```

Here’s the configuration as file based .thing file I’m using for the Deye Inverter:

```
Thing http:url:deye "Deye Inverter" [
    baseURL="http://192.168.178.33/status.html",
    header="",
    authMode="BASIC",
    username="secret",
    password="secret",
    ignoreSSLErrors=true,
    delay=0,
    stateMethod="GET",
    refresh=60,
    commandMethod="GET",
    strictErrorHandling=true,
    timeout=3000,
    bufferSize=2048,
    refresh=15] {
        Channels:
         Type number : energyTotal "Energy Total" [ mode="READONLY", stateTransformation="REGEX:.*var webdata_total_e = \"([0-9]+[\\.][0-9]+).*"]
         Type number : currentPower "current Power" [ mode="READONLY", stateTransformation="REGEX:.*var webdata_now_p = \"([0-9]+).*"]
}
```

The Yaml config looks like:

```
UID: http:url:deye
label: Deye Inverter
thingTypeUID: http:url
configuration:
  ignoreSSLErrors: true
  strictErrorHandling: true
  stateMethod: GET
  refresh: 15
  commandMethod: GET
  timeout: 3000
  authMode: BASIC
  baseURL: http://192.168.178.33/status.html
  password: password
  delay: 0
  header: ""
  username: user
  bufferSize: 2048
channels:
  - id: last-failure
    channelTypeUID: http:request-date-time
    label: Last Failure
    configuration: {}
  - id: last-success
    channelTypeUID: http:request-date-time
    label: Last Success
    configuration: {}
  - id: energyTotal
    channelTypeUID: http:number
    label: Energy Total
    configuration:
      mode: READONLY
      stateTransformation:
        - 'REGEX:.*var webdata_total_e = "([0-9]+[\.][0-9]+).* ∩JS: |
          (parseFloat(input) > 0) ? input : 0'
  - id: currentPower
    channelTypeUID: http:number
    label: current Power
    configuration:
      mode: READONLY
      stateTransformation:
        - REGEX:.*var webdata_now_p = "([0-9]+).*
```

The error suggests that http:url:deye:last-success and http:url:deye:last-failure are missing, but they are autogenerated and I don't have created these channels explicitly.

Has anyone else encountered a similar issue with HTTP bindings in OpenHAB?
How should I define or remove these missing channels?
Any help or insight would be greatly appreciated!

Thanks!
