### ISSUE TITLE
Unable to use pushover from rule UI due to " Required input "message" of the condition "2" not connected"

### ISSUE THREAD

**Issue by plysdyret** [openhab/openhab-core#4676]
Redirected here from the [forum](https://community.openhab.org/t/validation-of-rule-test-pushover-has-failed-required-input-message-of-the-condition-2-not-connected)

Trying to create a rule that will send a message with pushover but unable to save it due to:

```
Validation of rule test_pushover has failed! Required input "message" of the condition "2" not connected
```

The generated code looks fine to me:

```yaml
configuration: {}
triggers:
  - id: "1"
    configuration:
      cronExpression: 0 * * * * ? *
    type: timer.GenericCronTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      message: Meep
      title: openHAB
      config: pushover:pushover-account:test
    type: pushover.sendHtmlMessage#9e8ead2776057c93222de16046c654cf
```

## Expected behavior

Rule works

## Steps to reproduce

Create a rule and try to use any pushover action with a message.

## Your environment

Podman running openhab:latest

```yaml
runtimeInfo:
  version: 4.3.3
  buildString: Release Build
locale: en-US
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.14
  javaVendor: Debian
  osName: Linux
  osVersion: 5.14.0-503.22.1.el9_5.x86_64
  osArchitecture: amd64
  availableProcessors: 12
  freeMemory: 114918136
  totalMemory: 486539264
  uptime: 18952
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-amazonechocontrol
  - binding-androiddebugbridge
  - binding-androidtv
  - binding-astro
  - binding-boschindego
  - binding-boschshc
  - binding-chromecast
  - binding-exec
  - binding-homeconnect
  - binding-hpprinter
  - binding-icloud
  - binding-ipcamera
  - binding-ipp
  - binding-logreader
  - binding-meater
  - binding-mqtt
  - binding-pushover
  - binding-shelly
  - binding-sonos
  - binding-tradfri
  - binding-upnpcontrol
  - misc-openhabcloud
  - persistence-influxdb
  - transformation-exec
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - transformation-xslt
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - en-GB
      - en
      - da
    onLine: true
    platform: Win32
  screen:
    width: 5120
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
    blocklyRenderer: null
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/133.0.0.0 Safari/537.36
timestamp: 2025-02-24T17:44:23.906Z

```

## Browser console

Nothing in the logs, error only showing in the UI.

Some screenshots:

![Image](https://github.com/user-attachments/assets/2135854e-491b-459b-956b-41bc29297cdc)

![Image](https://github.com/user-attachments/assets/9f96af79-ba2c-49db-9e84-78fd164dae03)

This scripts works fine:

![Image](https://github.com/user-attachments/assets/efcbda68-50b1-4aa2-8771-bce0a25fa445)
