### ISSUE TITLE
[Regression] States of nested group members are not restored at startup since 5.0.0.M2

### ISSUE THREAD

**Issue by LukasA83** [openhab/openhab-core#4736]
I am using MapDB to restore values at startup. Since 5 M2 the values of nested group members are not restored. 
Persistance config:

```
configurations:
  - items:
      - gRestoreOnStartup*
    strategies:
      - everyChange
      - restoreOnStartup
    filters: []
cronStrategies: []
defaultStrategies:
  - everyChange
thresholdFilters: []
timeFilters: []
equalsFilters: []
includeFilters: []
```

Steps to reproduce:
Group setup:
"gRestoreOnStartup" has a child group item called "gChildRestore". "gChildRestore" has a child called "xyz". State is getting restored in 5.0.0.M1 but not in M2.
